// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetClassList():Promise<Array<string>>;

export function GetSaveFormat():Promise<string>;

export function LoadClassFile():Promise<Array<string>>;

export function LoadImage(arg1:number):Promise<main.ImageData>;

export function NextImage():Promise<main.ImageData>;

export function OpenDirectory(arg1:string):Promise<Array<main.FileInfo>>;

export function PrevImage():Promise<main.ImageData>;

export function SaveAnnotations(arg1:main.AnnotationData):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectSaveDirectory():Promise<string>;

export function SetSaveFormat(arg1:string):Promise<void>;
