// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClassList() {
  return window['go']['main']['App']['GetClassList']();
}

export function GetSaveFormat() {
  return window['go']['main']['App']['GetSaveFormat']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function LoadClassFile() {
  return window['go']['main']['App']['LoadClassFile']();
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function NextImage() {
  return window['go']['main']['App']['NextImage']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function PrevImage() {
  return window['go']['main']['App']['PrevImage']();
}

export function SaveAnnotations(arg1) {
  return window['go']['main']['App']['SaveAnnotations'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}

export function SetSaveFormat(arg1) {
  return window['go']['main']['App']['SetSaveFormat'](arg1);
}
